--- #YAML:1.0
name:               Apache-AuthTicket
version:            0.90
abstract:           Ticket based authentication system for Apache
author:
    - Michael Schout <mschout@gkg.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Apache2::AuthCookie:  3.0
    Apache::Test:         1.22
    DBI:                  0
    Digest::MD5:          0
    mod_perl2:            1.9922
    SQL::Abstract:        0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
